version: '3.8'

services:
  susan-ai-pgvector:
    image: pgvector/pgvector:pg16
    container_name: susan-ai-pgvector
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=susan_ai
    volumes:
      - susan-ai-pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  susan-ai-pgdata:
