spring.application.name=susan-ai
server.port=7000
#spring.ai.zhipuai.api-key=你自己申请的智谱AI大模型的key

spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.model=deepseek-r1:8b
#spring.ai.openai.api-key=${your.deepseek.key}
#spring.ai.openai.base-url=https://api.deepseek.com
#spring.ai.openai.base-url=https://api.deepseek.com/chat/completions
spring.ai.openai.chat.options.model=deepseek-chat

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html