brokerClusterName=DefaultCluster
brokerName=broker-a
brokerId=0
namesrvAddr=rocketmq-namesrv:9876
listenPort=10911
autoCreateTopicEnable=true
deleteWhen=04
fileReservedTime=48
storePathRootDir=/home/rocketmq/store
storePathCommitLog=/home/rocketmq/store/commitlog
